### ISSUE TITLE
Tracking Issue: Move Secure Software Factory Repo to OpenSSF!

### ISSUE THREAD

**Issue by dlorenc** [ossf/wg-supply-chain-integrity#47]
The Secure Software Factory (https://github.com/thesecuresoftwarefactory/ssf) that was demoed on the 19th is now approved to move into the OpenSSF under this WG.

We have a few logistical items to handle:

- [ ] Check the license/contribution guidelines
- [ ] Add the OSSF Code of Conduct: https://github.com/ossf/scorecard/blob/main/CODE_OF_CONDUCT.md
- [ ] Transfer the repository itself! I think I have the right permissions to accept the transfer once initiated

We should aim to do this by Tuesday for the announcement on Wednesday!

**Comment by dlorenc** [comment]
cc @mlieberman85

**Comment by dlorenc** [comment]
Just to clarify for anyone following along - after the demo meeting on 19th and a discussion in Slack on the 20th we've formally accepted the SSF to join the Supply Chain Integrity WG! This issue is tracking the logistical details required for the move itself.

**Comment by mlieberman85** [comment]
@dlorenc I think it's worthwhile to maybe do another refresh of this. We've been merged in, and I worked with Jory and others to make sure org falls under LF/OpenSSF ownership, however I think there might be a handful of license, CoC and other things that might be missing.

**Comment by dlorenc** [comment]
@mlieberman85 could you send an update to the README to add the FRSCA project, then close this out?

**Comment by mlieberman85** [comment]
Yes, let me do that right now.

**Comment by melba-lopez** [comment]
@mlieberman85 this issue appears to have been resolved per PR#54.  Is that correct?
